import { IContruction } from 'types';

export const data: IContruction[] = [
  {
    key: '1',
    number: 1,
    manufacturer: 'UnionDM',
    construction: 'Дверь',
    collection: 'Col',
    model: 'Invisible',
    finish: 'Fondo',
    width: 800,
    height: 2100,
    frame: 'Invisible',
    opening: 'L',
    casing: '',
    quantity: 1,
    pricelistPrice: 145019,
    price: 142838,
    sum: 198234,
    comment: 'Тестовый комментарий',
  },
  {
    key: '2',
    number: 2,
    manufacturer: 'UnionDM',
    construction: 'Перегородка',
    collection: 'Коллекция',
    model: 'Fly',
    finish: 'Alu Black',
    width: 2000,
    height: 3000,
    frame: '',
    opening: '',
    casing: '',
    quantity: 1,
    pricelistPrice: 981238,
    price: 981238,
    sum: 981238,
    comment: 'комментарий',
  },
];
